blank_issues_enabled: false
contact_links:
  - name: Sicherheitsproblem melden
    url: https://github.com/ooehme/tt5-caldav-calender/security/advisories/new
    about: Sicherheitsprobleme bitte ausschließlich privat melden.
