name: Funktionswunsch
description: Eine konkrete Verbesserung vorschlagen
title: '[Feature] '
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Ausgangsproblem
      description: Welches Problem soll gelöst werden?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Vorschlag
      description: Wie könnte eine gute Lösung aussehen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativen
      description: Welche Umgehungen oder Alternativen wurden bereits geprüft?
